### ISSUE TITLE
Продажа крон

### ISSUE THREAD

**Issue by eaglemoor** [eaglemoor/teso#4]
# User story

Для удобства ведения кроного магазина необходим бот, который предоставит удобный шаблон для подачи заявки на покупку кроновых вещей, будет вести логи по покупкам, предоставлять удобную аналитику для ГМ с метриками и графиками о покупках, автоматическое оповещение ГМ о подаче заявки (push на телефон)

При получении определенной популярности мы можем добавить поддержку iOS приложения для торговцев

**Comment by Erraida** [comment]
У меня есть бот для этого (Есть здесть в репозитории. Могу кинуть инвайт.).

**Comment by eaglemoor** [comment]
Написал своего бота на Golang. Сейчас обкатывается в Avalon

**Comment by eaglemoor** [comment]
Реализовали http://crown.avalonteso.ru
